# Generated by Django 4.1.7 on 2023-05-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cargo',
        ),
    ]
