services:
  backend:
    build: .
    image: lucht_app
    ports:
      - 8000:8000
    env_file: .env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/lucht-db
    depends_on:
      - postgres
    command: wait-for-it postgres:5432 -- python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app


  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - ~/.postgres/todo_db/data/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DBS=lucht-db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

    # healthcheck:
    #   test: pg_isready -U postgres
    #   interval: 2s
    #   timeout: 10s
    #   retries: 5
    #   start_period: 3s

volumes:
  postgres: