# Generated by Django 4.1.7 on 2023-05-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freight',
            name='Km_destino',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='freight',
            name='Km_origem',
            field=models.IntegerField(default=0),
        ),
    ]
