# Generated by Django 4.1.7 on 2023-05-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0002_freight_km_destino_freight_km_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freight',
            name='frete_adiant_valor',
            field=models.CharField(
                max_length=10,
                verbose_name='Frete_adiantamento',
            ),
        ),
        migrations.AlterField(
            model_name='freight',
            name='frete_saldo_valor',
            field=models.CharField(
                max_length=10,
                verbose_name='Frete_adiantamento',
            ),
        ),
        migrations.AlterField(
            model_name='freight',
            name='pedagio_valor',
            field=models.CharField(
                max_length=10,
                verbose_name='Pedágio_valor',
            ),
        ),
    ]
