# Generated by Django 4.1.7 on 2023-06-16 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0003_delete_truckfees'),
        ('freight', '0002_alter_freight_options_alter_freight_caminhao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freight',
            options={
                'ordering': ('data',),
                'verbose_name': 'freight',
                'verbose_name_plural': 'freights',
            },
        ),
        migrations.AlterField(
            model_name='freight',
            name='caminhao',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='freights',
                to='truck.truck',
                verbose_name='caminhao',
            ),
        ),
    ]
