# Generated by Django 4.1.7 on 2023-05-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0003_alter_freight_frete_adiant_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freight',
            name='frete_adiant_valor',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='freight',
            name='frete_saldo_valor',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='freight',
            name='pedagio_valor',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
