# Generated by Django 4.1.7 on 2023-05-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('ano_fab', models.PositiveIntegerField()),
                ('placa', models.CharField(max_length=10)),
                ('Chassis', models.CharField(max_length=20)),
                ('odometro', models.PositiveIntegerField()),
            ],
        ),
    ]
