# Generated by Django 4.1.7 on 2023-06-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0002_truckfees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TruckFees',
        ),
    ]
