# Generated by Django 4.1.7 on 2023-06-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0004_alter_truck_options_truckflue'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckflue',
            name='litros',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
