# Generated by Django 4.1.7 on 2023-07-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0005_truckflue_litros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckflue',
            name='litros',
            field=models.FloatField(default=0),
        ),
    ]
