# Generated by Django 4.1.7 on 2023-08-07 19:01
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0006_alter_truckflue_litros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='truck',
            options={
                'ordering': ('placa',),
                'verbose_name': 'Truck',
                'verbose_name_plural': 'Trucks',
            },
        ),
        migrations.AlterModelOptions(
            name='truckflue',
            options={
                'ordering': ('data',),
                'verbose_name': 'TruckFlue',
                'verbose_name_plural': 'TruckFlues',
            },
        ),
        migrations.AlterField(
            model_name='truckflue',
            name='caminhao',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='truckflues',
                to='truck.truck',
                verbose_name='caminhao',
            ),
        ),
    ]
