# Generated by Django 4.1.7 on 2023-08-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0007_alter_truck_options_alter_truckflue_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckflue',
            name='descricao',
            field=models.CharField(default='Diesel', max_length=20),
        ),
    ]
