# Generated by Django 4.1.7 on 2023-08-15 19:12
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0008_truckflue_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckRepair',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('data', models.DateField()),
                (
                    'repair_valor',
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                ('descricao', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                (
                    'caminhao',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='truckrepairs',
                        to='truck.truck',
                        verbose_name='caminhao',
                    ),
                ),
            ],
            options={
                'verbose_name': 'truckrepair',
                'verbose_name_plural': 'truckrepairs',
                'ordering': ('data',),
            },
        ),
    ]
