# Generated by Django 4.1.7 on 2023-09-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0009_truckrepair'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckflue',
            name='cidade',
            field=models.CharField(
                blank=True,
                default='Pr-Curitiba',
                max_length=50,
            ),
        ),
    ]
