# Generated by Django 4.1.7 on 2023-05-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('nome', models.CharField(max_length=30)),
                ('email', models.CharField(blank=True, max_length=20)),
                ('cpf', models.CharField(max_length=11)),
                ('cnh', models.CharField(max_length=11)),
                ('data_nasc', models.DateField()),
                ('telefone', models.CharField(max_length=15)),
                ('rua', models.CharField(blank=True, max_length=50)),
                ('bairro', models.CharField(blank=True, max_length=30)),
                (
                    'cidade',
                    models.CharField(default='Curitiba', max_length=30),
                ),
                ('estado', models.CharField(default='Paraná', max_length=30)),
                ('cep', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
