# Generated by Django 4.1.7 on 2023-05-22 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='user',
            new_name='nome',
        ),
    ]
