name: Continous integration

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://jlplautz:lingara@localhost:5432/db_lucht

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: lingara
          POSTGRES_USER: jlplautz

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432    
    
    steps:
      - name: Copy files from repo
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.11.1
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.1'
          cache: pip

      - name: Instalar poetry
        run: pip install poetry

      - name: Install Dependencies 
        run: poetry install --without doc

      - name: Setup .env
        run: cp .env.example .env
    
      - name: Run Tests
        run: poetry run task test --cov-report=xml

      - name: Verificar cobertura via codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
